version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/Mexico_City"
    open-pull-requests-limit: 10
    groups:
      androidx:
        patterns:
          - "androidx*"
      google-android:
        patterns:
          - "com.android*"
          - "com.google*"
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
      squareup:
        patterns:
          - "com.squareup*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/Mexico_City"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
